title: GlareDB Docs
description: Documentation for GlareDB
theme: just-the-docs

url: https://docs.glaredb.com

favicon_ico: "/assets/images/favicon.svg"
logo: "/assets/images/logo.svg"

aux_links:
  Get access: https://glaredb.com

aux_links_new_tab: true

color_scheme: glaredb

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/glaredb/glaredb.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

enable_copy_code_button: false

callouts_level: quiet # or loud
callouts:
  important:
    title: Note
    color: blue
  new:
    title: New
    color: green
  warning:
    title: Warning
    color: yellow
