title: GlareDB Docs
description: Documentation for GlareDB
theme: just-the-docs

url: https://docs.glaredb.com
plugins:
  - jekyll-sitemap

favicon_ico: "/assets/favicon.svg"
logo: "/assets/logo.svg"

aux_links:
  GlareDB Cloud: https://console.glaredb.com
  Open source: https://github.com/glaredb/glaredb

aux_links_new_tab: true

color_scheme: glaredb

ga_tracking: G-QZTF07SKKQ

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/glaredb/glaredb.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

enable_copy_code_button: true

callouts_level: quiet # or loud
callouts:
  important:
    title: Note
    color: blue
  new:
    title: New
    color: green
  warning:
    title: Warning
    color: yellow
# collections:
# cloud:
#   permalink: "/:collection/:path/"
#   output: true
# glaredb:
#   permalink: "/:collection/:path/"
#   output: true

# just_the_docs:
# collections:
#   glaredb:
#     name: "GlareDB"
#   cloud:
#     name: "Cloud"
