title: GlareDB Docs
description: Documentation for GlareDB
theme: just-the-docs

url: https://just-the-docs.github.io

favicon_ico: "/assets/images/favicon.svg"
logo: "/assets/images/logo.svg"

aux_links:
  Get access: https://glaredb.com

aux_links_new_tab: true

color_scheme: glaredb
