name: Docs CI

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-format:
    name: Lint and format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format
